package fea

// This file would be auto-generated by the Freyja compiler
// when compiling a Freyja library with -emit-bindings flag
//
// Example: freyja compile matrix_ops.freyja -emit-bindings -o freyja_blas
//
// Would generate:
//   - freyja_blas.so/lib (compiled library)
//   - freyja_blas_bindings.odin (this file)

import "core:c"

when ODIN_OS == .Windows {
    foreign import freyja_blas "freyja_blas.lib"
} else when ODIN_OS == .Linux {
    foreign import freyja_blas "freyja_blas.so"
} else when ODIN_OS == .Darwin {
    foreign import freyja_blas "freyja_blas.dylib"
}

@(default_calling_convention="c")
foreign freyja_blas {
    // Level 1 BLAS operations
    
    // y = a*x + y
    freyja_daxpy :: proc(n: c.int, a: c.double, x: [^]c.double, incx: c.int, y: [^]c.double, incy: c.int) ---
    
    // dot product: result = x . y
    freyja_ddot :: proc(n: c.int, x: [^]c.double, incx: c.int, y: [^]c.double, incy: c.int) -> c.double ---
    
    // Euclidean norm: result = ||x||_2
    freyja_dnrm2 :: proc(n: c.int, x: [^]c.double, incx: c.int) -> c.double ---
    
    // Scale vector: x = a*x
    freyja_dscal :: proc(n: c.int, a: c.double, x: [^]c.double, incx: c.int) ---
    
    // Copy vector: y = x
    freyja_dcopy :: proc(n: c.int, x: [^]c.double, incx: c.int, y: [^]c.double, incy: c.int) ---
    
    // Level 2 BLAS operations
    
    // Matrix-vector multiply: y = alpha*A*x + beta*y
    // trans: 'N' = no transpose, 'T' = transpose
    freyja_dgemv :: proc(trans: c.char, m: c.int, n: c.int, 
                         alpha: c.double, A: [^]c.double, lda: c.int,
                         x: [^]c.double, incx: c.int,
                         beta: c.double, y: [^]c.double, incy: c.int) ---
    
    // Symmetric matrix-vector multiply: y = alpha*A*x + beta*y
    freyja_dsymv :: proc(uplo: c.char, n: c.int,
                         alpha: c.double, A: [^]c.double, lda: c.int,
                         x: [^]c.double, incx: c.int,
                         beta: c.double, y: [^]c.double, incy: c.int) ---
    
    // Level 3 BLAS operations
    
    // General matrix-matrix multiply: C = alpha*A*B + beta*C
    // transA/transB: 'N' = no transpose, 'T' = transpose
    freyja_dgemm :: proc(transA: c.char, transB: c.char,
                         m: c.int, n: c.int, k: c.int,
                         alpha: c.double, A: [^]c.double, lda: c.int,
                         B: [^]c.double, ldb: c.int,
                         beta: c.double, C: [^]c.double, ldc: c.int) ---
    
    // Symmetric matrix-matrix multiply: C = alpha*A*B + beta*C (or B*A)
    freyja_dsymm :: proc(side: c.char, uplo: c.char,
                         m: c.int, n: c.int,
                         alpha: c.double, A: [^]c.double, lda: c.int,
                         B: [^]c.double, ldb: c.int,
                         beta: c.double, C: [^]c.double, ldc: c.int) ---
    
    // Triangular matrix solve: X = A^-1 * B
    freyja_dtrsm :: proc(side: c.char, uplo: c.char, transA: c.char, diag: c.char,
                         m: c.int, n: c.int,
                         alpha: c.double, A: [^]c.double, lda: c.int,
                         B: [^]c.double, ldb: c.int) ---
    
    // LAPACK-like operations
    
    // LU decomposition with partial pivoting
    freyja_dgetrf :: proc(m: c.int, n: c.int, A: [^]c.double, lda: c.int, 
                          ipiv: [^]c.int, info: ^c.int) ---
    
    // Solve system using LU decomposition
    freyja_dgetrs :: proc(trans: c.char, n: c.int, nrhs: c.int,
                          A: [^]c.double, lda: c.int, ipiv: [^]c.int,
                          B: [^]c.double, ldb: c.int, info: ^c.int) ---
    
    // Cholesky decomposition
    freyja_dpotrf :: proc(uplo: c.char, n: c.int, A: [^]c.double, lda: c.int, info: ^c.int) ---
    
    // Solve system using Cholesky decomposition  
    freyja_dpotrs :: proc(uplo: c.char, n: c.int, nrhs: c.int,
                          A: [^]c.double, lda: c.int,
                          B: [^]c.double, ldb: c.int, info: ^c.int) ---
}

// Convenience wrappers that convert Odin slices to C pointers
// These would also be auto-generated

daxpy :: proc(n: int, a: f64, x: []f64, y: []f64) {
    freyja_daxpy(c.int(n), c.double(a), raw_data(x), 1, raw_data(y), 1)
}

ddot :: proc(n: int, x: []f64, y: []f64) -> f64 {
    return f64(freyja_ddot(c.int(n), raw_data(x), 1, raw_data(y), 1))
}

dnrm2 :: proc(n: int, x: []f64) -> f64 {
    return f64(freyja_dnrm2(c.int(n), raw_data(x), 1))
}

dgemv :: proc(m: int, n: int, alpha: f64, A: []f64, x: []f64, beta: f64, y: []f64) {
    freyja_dgemv('N', c.int(m), c.int(n), 
                 c.double(alpha), raw_data(A), c.int(n),
                 raw_data(x), 1,
                 c.double(beta), raw_data(y), 1)
}

dgemm :: proc(m: int, n: int, k: int, alpha: f64, A: []f64, B: []f64, beta: f64, C: []f64) {
    freyja_dgemm('N', 'N', c.int(m), c.int(n), c.int(k),
                 c.double(alpha), raw_data(A), c.int(m),
                 raw_data(B), c.int(k),
                 c.double(beta), raw_data(C), c.int(m))
}

// Additional metadata that could be embedded
FREYJA_VERSION :: "0.1.0"
FREYJA_BUILD_DATE :: "2025-01-10"
FREYJA_COMPILER_FLAGS :: "-O3 -march=native -ffast-math"