package fea

// Auto-generated by Freyja compiler
// freyja compile matrix_ops.freyja -emit-odin-bindings -o freyja_lib

import "core:c"

when ODIN_OS == .Windows {
    // Windows: .lib for static, .dll for dynamic
    foreign import freyja_lib "freyja_lib.lib"
} else when ODIN_OS == .Darwin {
    // macOS: .a for static, .dylib for dynamic
    foreign import freyja_lib "freyja_lib.a"
    // Or for dynamic: foreign import freyja_lib "freyja_lib.dylib"
} else when ODIN_OS == .Linux {
    // Linux: .a for static, .so for dynamic
    foreign import freyja_lib "freyja_lib.a"
    // Or for dynamic: foreign import freyja_lib "freyja_lib.so"
}

// Freyja Matrix Types (matches Freyja's internal representation)
// Column-major storage for optimal BLAS performance

Matrix :: struct {
    data: [^]f64,
    rows: int,
    cols: int,
    stride: int,  // For sub-matrix views
}

Vector :: struct {
    data: [^]f64,
    size: int,
    stride: int,  // For strided access
}

// Matrix creation helpers
matrix :: proc(rows, cols: int, allocator := context.allocator) -> Matrix {
    data := make([]f64, rows * cols, allocator)
    return Matrix{
        data = raw_data(data),
        rows = rows,
        cols = cols,
        stride = rows,  // Column-major
    }
}

vector :: proc(size: int, allocator := context.allocator) -> Vector {
    data := make([]f64, size, allocator)
    return Vector{
        data = raw_data(data),
        size = size,
        stride = 1,
    }
}

// View into existing data
matrix_view :: proc(data: []f64, rows, cols: int) -> Matrix {
    return Matrix{
        data = raw_data(data),
        rows = rows,
        cols = cols,
        stride = rows,
    }
}

vector_view :: proc(data: []f64) -> Vector {
    return Vector{
        data = raw_data(data),
        size = len(data),
        stride = 1,
    }
}

// Foreign function declarations (hidden from user)
@(private)
foreign freyja_lib {
    @(link_name="freyja_mul_mat_mat")
    _mul_mat_mat :: proc(A: ^Matrix, B: ^Matrix, C: ^Matrix) ---
    
    @(link_name="freyja_mul_mat_vec")
    _mul_mat_vec :: proc(A: ^Matrix, x: ^Vector, y: ^Vector) ---
    
    @(link_name="freyja_mul_vec_scalar")
    _mul_vec_scalar :: proc(x: ^Vector, alpha: f64, y: ^Vector) ---
    
    @(link_name="freyja_add_vec_vec")
    _add_vec_vec :: proc(x: ^Vector, y: ^Vector, result: ^Vector) ---
    
    @(link_name="freyja_add_mat_mat")
    _add_mat_mat :: proc(A: ^Matrix, B: ^Matrix, C: ^Matrix) ---
    
    @(link_name="freyja_dot_vec_vec")
    _dot_vec_vec :: proc(x: ^Vector, y: ^Vector) -> f64 ---
    
    @(link_name="freyja_norm_vec")
    _norm_vec :: proc(x: ^Vector) -> f64 ---
    
    @(link_name="freyja_transpose_mat")
    _transpose_mat :: proc(A: ^Matrix, AT: ^Matrix) ---
    
    @(link_name="freyja_solve_linear")
    _solve_linear :: proc(A: ^Matrix, b: ^Vector, x: ^Vector) -> c.int ---
    
    @(link_name="freyja_inverse_mat")
    _inverse_mat :: proc(A: ^Matrix, Ainv: ^Matrix) -> c.int ---
    
    @(link_name="freyja_decompose_lu")
    _decompose_lu :: proc(A: ^Matrix, L: ^Matrix, U: ^Matrix, P: [^]c.int) -> c.int ---
    
    @(link_name="freyja_decompose_cholesky")
    _decompose_cholesky :: proc(A: ^Matrix, L: ^Matrix) -> c.int ---
    
    @(link_name="freyja_decompose_qr")
    _decompose_qr :: proc(A: ^Matrix, Q: ^Matrix, R: ^Matrix) -> c.int ---
    
    @(link_name="freyja_eigenvalues")
    _eigenvalues :: proc(A: ^Matrix, eigenvals: ^Vector, eigenvecs: ^Matrix) -> c.int ---
}

// =====================================
// High-level ergonomic API with proc groups
// =====================================

// Multiplication proc group
mul :: proc{mul_mat_mat, mul_mat_vec, mul_vec_scalar, mul_scalar_vec, mul_scalar_mat}

mul_mat_mat :: proc(A, B: Matrix, allocator := context.allocator) -> Matrix {
    C := matrix(A.rows, B.cols, allocator)
    _mul_mat_mat(&A, &B, &C)
    return C
}

mul_mat_vec :: proc(A: Matrix, x: Vector, allocator := context.allocator) -> Vector {
    y := vector(A.rows, allocator)
    _mul_mat_vec(&A, &x, &y)
    return y
}

mul_vec_scalar :: proc(x: Vector, alpha: f64, allocator := context.allocator) -> Vector {
    y := vector(x.size, allocator)
    _mul_vec_scalar(&x, alpha, &y)
    return y
}

mul_scalar_vec :: proc(alpha: f64, x: Vector, allocator := context.allocator) -> Vector {
    return mul_vec_scalar(x, alpha, allocator)
}

mul_scalar_mat :: proc(alpha: f64, A: Matrix, allocator := context.allocator) -> Matrix {
    B := matrix(A.rows, A.cols, allocator)
    for i in 0..<(A.rows * A.cols) {
        B.data[i] = alpha * A.data[i]
    }
    return B
}

// Addition proc group
add :: proc{add_mat_mat, add_vec_vec}

add_mat_mat :: proc(A, B: Matrix, allocator := context.allocator) -> Matrix {
    C := matrix(A.rows, A.cols, allocator)
    _add_mat_mat(&A, &B, &C)
    return C
}

add_vec_vec :: proc(x, y: Vector, allocator := context.allocator) -> Vector {
    result := vector(x.size, allocator)
    _add_vec_vec(&x, &y, &result)
    return result
}

// Dot product
dot :: proc(x, y: Vector) -> f64 {
    return _dot_vec_vec(&x, &y)
}

// Norm
norm :: proc(x: Vector) -> f64 {
    return _norm_vec(&x)
}

// Transpose
transpose :: proc(A: Matrix, allocator := context.allocator) -> Matrix {
    AT := matrix(A.cols, A.rows, allocator)
    _transpose_mat(&A, &AT)
    return AT
}

// Linear solve proc group
solve :: proc{solve_linear, solve_triangular, solve_symmetric}

solve_linear :: proc(A: Matrix, b: Vector, allocator := context.allocator) -> (Vector, bool) {
    x := vector(b.size, allocator)
    status := _solve_linear(&A, &b, &x)
    return x, status == 0
}

solve_triangular :: proc(A: Matrix, b: Vector, upper := true, allocator := context.allocator) -> Vector {
    // Specialized triangular solve
    x := vector(b.size, allocator)
    // Implementation would call specialized Freyja function
    return x
}

solve_symmetric :: proc(A: Matrix, b: Vector, allocator := context.allocator) -> Vector {
    // Specialized symmetric solve (using Cholesky)
    x := vector(b.size, allocator)
    // Implementation would call specialized Freyja function
    return x
}

// Matrix inverse
inverse :: proc(A: Matrix, allocator := context.allocator) -> (Matrix, bool) {
    Ainv := matrix(A.rows, A.cols, allocator)
    status := _inverse_mat(&A, &Ainv)
    return Ainv, status == 0
}

// Decomposition proc group
decompose :: proc{decompose_lu, decompose_cholesky, decompose_qr, decompose_svd}

Decomposition_LU :: struct {
    L, U: Matrix,
    P: []int,
}

decompose_lu :: proc(A: Matrix, allocator := context.allocator) -> (Decomposition_LU, bool) {
    result: Decomposition_LU
    result.L = matrix(A.rows, A.rows, allocator)
    result.U = matrix(A.rows, A.cols, allocator)
    result.P = make([]int, A.rows, allocator)
    
    P_c := make([]c.int, A.rows, allocator)
    defer delete(P_c)
    
    status := _decompose_lu(&A, &result.L, &result.U, raw_data(P_c))
    
    for i, p in P_c {
        result.P[i] = int(p)
    }
    
    return result, status == 0
}

decompose_cholesky :: proc(A: Matrix, allocator := context.allocator) -> (Matrix, bool) {
    L := matrix(A.rows, A.cols, allocator)
    status := _decompose_cholesky(&A, &L)
    return L, status == 0
}

Decomposition_QR :: struct {
    Q, R: Matrix,
}

decompose_qr :: proc(A: Matrix, allocator := context.allocator) -> (Decomposition_QR, bool) {
    result: Decomposition_QR
    result.Q = matrix(A.rows, A.rows, allocator)
    result.R = matrix(A.rows, A.cols, allocator)
    status := _decompose_qr(&A, &result.Q, &result.R)
    return result, status == 0
}

Decomposition_SVD :: struct {
    U, S, V: Matrix,
}

decompose_svd :: proc(A: Matrix, allocator := context.allocator) -> (Decomposition_SVD, bool) {
    // SVD implementation
    result: Decomposition_SVD
    // Would call Freyja SVD function
    return result, true
}

// Eigenvalues/eigenvectors
eigen :: proc(A: Matrix, allocator := context.allocator) -> (values: Vector, vectors: Matrix, ok: bool) {
    values = vector(A.rows, allocator)
    vectors = matrix(A.rows, A.rows, allocator)
    status := _eigenvalues(&A, &values, &vectors)
    ok = status == 0
    return
}

// Convenience operators (could be added to Odin with operator overloading)
// For now, these are just procs

// A * B for matrices
mat_mul :: proc(A, B: Matrix) -> Matrix {
    return mul(A, B)
}

// A * x for matrix-vector
mat_vec_mul :: proc(A: Matrix, x: Vector) -> Vector {
    return mul(A, x)
}

// Element access helpers
at :: proc{mat_at, vec_at}

mat_at :: proc(m: Matrix, i, j: int) -> f64 {
    return m.data[j * m.stride + i]  // Column-major
}

vec_at :: proc(v: Vector, i: int) -> f64 {
    return v.data[i * v.stride]
}

set :: proc{mat_set, vec_set}

mat_set :: proc(m: ^Matrix, i, j: int, val: f64) {
    m.data[j * m.stride + i] = val
}

vec_set :: proc(v: ^Vector, i: int, val: f64) {
    v.data[i * v.stride] = val
}

// Pretty printing
print :: proc{print_matrix, print_vector}

print_matrix :: proc(m: Matrix, name := "Matrix") {
    fmt.printf("%s [%d×%d]:\n", name, m.rows, m.cols)
    for i in 0..<m.rows {
        for j in 0..<m.cols {
            fmt.printf("%8.3f ", at(m, i, j))
        }
        fmt.println()
    }
}

print_vector :: proc(v: Vector, name := "Vector") {
    fmt.printf("%s [%d]: ", name, v.size)
    for i in 0..<v.size {
        fmt.printf("%8.3f ", at(v, i))
    }
    fmt.println()
}